name: Deployment websms
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REMOTE_HUB_NAME }}
          password: ${{ secrets.REMOTE_HUB_PASSWD }}
      - name: Navigate to project folder
        run: |
          cd /home/trex18/runner-websms/_work/
      - name: Pull latest images from compose
        run: |
          docker compose pull
      - name: Recreate and start containers
        run: |
          docker compose down
          docker compose up -d
          #docker compose up -d --remove-orphans
